In [1]:
import pandas as pd

In [3]:
racesfr = pd.read_parquet("../racesfr.parquet") 
racesfr

,Score,penalty,Div,Sailor,Link,key,GradYear,Position,Partner,Venue,...,adjusted_raceID,Date,raceNum,Team,Teamlink,Boat,TeamBoatName,updatedAt,PartnerLink,partnerKey
0,6.0,,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,...,s10/icsa-gill-coed-dinghy-champs/1A,2010-06-01,1,Boston College,boston-college,420,Eagles,1.789780e+09,Unknown,Laura McKenna-Boston College
1,5.0,,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,...,s10/icsa-gill-coed-dinghy-champs/2A,2010-06-01,2,Boston College,boston-college,420,Eagles,1.789780e+09,Unknown,Laura McKenna-Boston College
2,15.0,,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,...,s10/icsa-gill-coed-dinghy-champs/3A,2010-06-01,3,Boston College,boston-college,420,Eagles,1.789780e+09,Unknown,Laura McKenna-Boston College
3,2.0,,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,...,s10/icsa-gill-coed-dinghy-champs/4A,2010-06-01,4,Boston College,boston-college,420,Eagles,1.789780e+09,Unknown,Laura McKenna-Boston College
4,8.0,,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Lucy Wallace,Wisconsin,...,s10/icsa-gill-coed-dinghy-champs/5A,2010-06-01,5,Boston College,boston-college,420,Eagles,1.789780e+09,Unknown,Lucy Wallace-Boston College
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503268,10.0,,B,Sydney Woodard,Unknown,Sydney Woodard-Michigan State,29 *,Crew,Austin Sjarda,Michigan Tech,...,f26/gavin/2B,2026-09-05,2,Michigan State,michigan-state,420,Spartans,1.789781e+09,Unknown,Austin Sjarda-Michigan State
1503269,7.0,,B,Sydney Woodard,Unknown,Sydney Woodard-Michigan State,29 *,Crew,Austin Sjarda,Michigan Tech,...,f26/gavin/4B,2026-09-05,4,Michigan State,michigan-state,420,Spartans,1.789781e+09,Unknown,Austin Sjarda-Michigan State
1503270,10.0,,B,Sydney Woodard,Unknown,Sydney Woodard-Michigan State,29 *,Crew,Austin Sjarda,Michigan Tech,...,f26/gavin/6B,2026-09-05,6,Michigan State,michigan-state,420,Spartans,1.789781e+09,Unknown,Austin Sjarda-Michigan State
1503271,9.0,,B,Sydney Woodard,Unknown,Sydney Woodard-Michigan State,29 *,Crew,Austin Sjarda,Michigan Tech,...,f26/gavin/8B,2026-09-05,8,Michigan State,michigan-state,420,Spartans,1.789781e+09,Unknown,Austin Sjarda-Michigan State
1503272,11.0,DNS,B,Sydney Woodard,Unknown,Sydney Woodard-Michigan State,29 *,Crew,Austin Sjarda,Michigan Tech,...,f26/gavin/10B,2026-09-05,10,Michigan State,michigan-state,420,Spartans,1.789781e+09,Unknown,Austin Sjarda-Michigan State

In [4]:
sailor_data = pd.read_parquet("../sailor_data2.parquet") 
sailor_data

,key,link,name,first_name,last_name,gender,year,teamLink,team,id,external_id
0,aadi-sethi,aadi-sethi,Aadi Sethi,Aadi,Sethi,M,2029,boston-universit,Boston University,3137877.0,None
1,aadvika-ahuja,aadvika-ahuja,aadvika ahuja,aadvika,ahuja,F,2025,uc-davi,UC Davis,3136210.0,None
2,aaron-babier,aaron-babier,Aaron Babier,Aaron,Babier,M,2015,quee,Queen's,1263635.0,19675
3,aaron-blust,aaron-blust,Aaron Blust,Aaron,Blust,M,2024,oli,Olin,3127882.0,None
4,aaron-burnett,aaron-burnett,Aaron Burnett,Aaron,Burnett,M,2019,florid,Florida,3114274.0,27657
...,...,...,...,...,...,...,...,...,...,...,...
305780,Elsa Fellon-Virginia,None,Elsa Fellon,None,None,None,29 *,None,Virginia,NaN,None
305781,Elsa Fellon-Virginia,None,Elsa Fellon,None,None,None,29 *,None,Virginia,NaN,None
305782,Elsa Fellon-Virginia,None,Elsa Fellon,None,None,None,29 *,None,Virginia,NaN,None
305783,Elsa Fellon-Virginia,None,Elsa Fellon,None,None,None,29 *,None,Virginia,NaN,None
305784,Elsa Fellon-Virginia,None,Elsa Fellon,None,None,None,29 *,None,Virginia,NaN,None