In [1]:
import pandas as pd
from openskill.models import PlackettLuce
from Sailors import Sailor

In [2]:

temp = pd.read_json("./../sailors-latest.json")
# temp = pd.read_parquet("./../sailorLatestInfoOnly.parquet")

In [3]:
temp.drop(columns=['Seasons','Rivals', 'Races'])
temp.to_parquet('./../sailorLatestInfoOnly.parquet')
temp

:

:

In [ ]:
def make_sailor(args):
    key, link, name, first_name, last_name, gender, year, teamLink, team, id, external_id = args
    model = PlackettLuce(beta=25.0 / 120.0)
    rating = model.rating
    return key, Sailor(
        name, key, gender, year,
        [link], [team],
        seasons={'skipper': [], 'crew': []},
        races=[], rivals={},
        sr=rating(), cr=rating(), wsr=rating(), wcr=rating(),
        tsr=rating(), tcr=rating(), wtsr=rating(), wtcr=rating()
    )

In [ ]:
def updateSailorRatings(args):
    Sailor, numRaces, key, SkipperRank, CrewRank, WomenSkipperRank, WomenCrewRank, TRSkipperRank, TRWomenSkipperRank, Teams, gender, srOrd, crOrd, wsrOrd, wcrOrd, tsrOrd, tcrOrd, wtsrOrd, wtcrOrd, srMU, srSigma, crMU, crSigma, wsrMU, wsrSigma, wcrMU, wcrSigma, tsrMU, tsrSigma, tcrMU, tcrSigma, wtsrMU, wtsrSigma, wtcrMU, wtcrSigma, outLinks, GradYear, Links, Seasons, Cross, Races, Rivals, skipperAvgRatio, crewAvgRatio, people = args
    
    sailor = people[key]
    
    sailor.sr.mu = srMU
    sailor.sr.sigma = srSigma
    
    sailor.cr.mu = crMU
    sailor.cr.sigma = crSigma
    
    sailor.wsr.mu = wsrMU
    sailor.wsr.sigma = wsrSigma
    
    sailor.wcr.mu = wcrMU
    sailor.wcr.sigma = wcrSigma
    
    sailor.tsr.mu = tsrMU
    sailor.tsr.sigma = tsrSigma
    
    sailor.tcr.mu = tcrMU
    sailor.tcr.sigma = tcrSigma
    
    sailor.wtsr.mu = wtsrMU
    sailor.wtsr.sigma = wtsrSigma
    
    sailor.wtcr.mu = wtcrMU
    sailor.wtcr.sigma = wtcrSigma

In [2]:
test = pd.read_json("./../sailors-latest.json")

In [3]:
# test = pd.read_json("./../sailors-latest.json")
# test = pd.read_json("./../racesfrtest.json")
# test.to_parquet("racesfrtest.parquet", index=False)
test = pd.read_parquet("./../postcalcfrraces.parquet")
# test = pd.read_parquet("./../f25-34th-captain-hurst-bowl.parquet")
# test.loc[test['key'] == 'gabriel-gabe-morreale-2028', 'id'] = 3138450
# test['id'] = pd.to_numeric(test['id'], errors='coerce', downcast='integer')
# test.to_parquet("./../sailors-latest.parquet", index=False)
test

,raceID,season,regatta,raceNumber,div,sailorID,partnerID,partnerName,score,predicted,...,date,scoring,venue,boat,boatName,ratingType,oldRating,newRating,regAvg:,calculatedAt
0,s10/harris-l-kempner/5B,s10,harris-l-kempner,5,B,Justin Ogden-Texas,Unknown,Brandon Fiew,5,1,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 1,sr,1000.000000,1097.767333,1000.000000,1.770705e+09
1,s10/harris-l-kempner/5B,s10,harris-l-kempner,5,B,Pierre Rochard-Texas,Unknown,Unknown,11,2,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 2,sr,1000.000000,956.383077,1000.000000,1.770705e+09
2,s10/harris-l-kempner/6B,s10,harris-l-kempner,6,B,Justin Ogden-Texas,Unknown,Unknown,5,1,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 1,sr,1097.767333,1172.116321,1000.000000,1.770705e+09
3,s10/harris-l-kempner/6B,s10,harris-l-kempner,6,B,Pierre Rochard-Texas,Unknown,Unknown,11,2,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 2,sr,956.383077,930.268574,1000.000000,1.770705e+09
4,s10/harris-l-kempner/7B,s10,harris-l-kempner,7,B,Justin Ogden-Texas,Unknown,Unknown,6,1,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 1,sr,1172.116321,1228.541984,1000.000000,1.770705e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455216,s26/harris-kempner/2B,s26,harris-kempner,2,B,gage-krahulik,Unknown,Jamie Larson,6,2,...,2026-02-07,2 Divisions,Texas A&M Galveston,,Islanders,sr,1126.064778,1134.920545,1154.212642,1.770706e+09
1455217,s26/harris-kempner/2B,s26,harris-kempner,2,B,kalia-peterson,nathan-hjort,Nathan Hjort,2,2,...,2026-02-07,2 Divisions,Texas A&M Galveston,,Sailfish,cr,1029.245265,1072.912954,1154.212642,1.770706e+09
1455218,s26/harris-kempner/2B,s26,harris-kempner,2,B,annika-baumgartner,carsten-zieger,Carsten Zieger,1,1,...,2026-02-07,2 Divisions,Texas A&M Galveston,,Bears,cr,1553.714515,1585.653979,1154.212642,1.770706e+09
1455219,s26/harris-kempner/2B,s26,harris-kempner,2,B,evelyn-chase,macie-bettis,Macie Bettis,8,4,...,2026-02-07,2 Divisions,Texas A&M Galveston,,Sea Aggies 2,cr,1000.000000,899.918165,1154.212642,1.770706e+09
1455220,s26/harris-kempner/2B,s26,harris-kempner,2,B,Jamie Larson-Texas A&M C. Christ,gage-krahulik,Gage Krahulik,6,3,...,2026-02-07,2 Divisions,Texas A&M Galveston,,Islanders,cr,912.661105,955.361634,1154.212642,1.770706e+09

# Testing sailor loading into object from file

In [2]:
import pandas as pd
from openskill.models import PlackettLuceRating
from config import Config
from Sailors import Sailor
import importlib

config = Config()

In [ ]:
df_sailor_info = pd.read_parquet("./../sailor_data2.parquet")

In [7]:
df_sailor_info.loc[df_sailor_info['key'] == 'carter-anderson'].iloc[0].to_dict()

{'key': 'carter-anderson',
 'link': 'carter-anderson',
 'name': 'Carter Anderson',
 'first_name': 'Carter',
 'last_name': 'Anderson',
 'gender': 'M',
 'year': '2027',
 'teamLink': 'uc-santa-cruz',
 'team': 'UC Santa Cruz',
 'id': 3133584.0,
 'external_id': None}

In [ ]:
df_sailor_ratings = pd.read_json("./../sailors-latest.json")
df_racesfr = pd.read_parquet("./../racesfrtest.parquet")

,Score,Div,Sailor,Link,key,GradYear,Position,Partner,Venue,Regatta,...,adjusted_raceID,Date,raceNum,Team,Teamlink,Boat,TeamBoatName,updatedAt,PartnerLink,partnerKey
0,6.0,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,s10/icsa-gill-coed-dinghy-champs,...,s10/icsa-gill-coed-dinghy-champs/1A,2010-06-01,1,Boston College,boston-college,420,Eagles,1.770488e+09,Unknown,Laura McKenna-Boston College
1,5.0,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,s10/icsa-gill-coed-dinghy-champs,...,s10/icsa-gill-coed-dinghy-champs/2A,2010-06-01,2,Boston College,boston-college,420,Eagles,1.770488e+09,Unknown,Laura McKenna-Boston College
2,15.0,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,s10/icsa-gill-coed-dinghy-champs,...,s10/icsa-gill-coed-dinghy-champs/3A,2010-06-01,3,Boston College,boston-college,420,Eagles,1.770488e+09,Unknown,Laura McKenna-Boston College
3,2.0,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Laura McKenna,Wisconsin,s10/icsa-gill-coed-dinghy-champs,...,s10/icsa-gill-coed-dinghy-champs/4A,2010-06-01,4,Boston College,boston-college,420,Eagles,1.770488e+09,Unknown,Laura McKenna-Boston College
4,8.0,A,Tyler Sinks,Unknown,Tyler Sinks-Boston College,11,Skipper,Lucy Wallace,Wisconsin,s10/icsa-gill-coed-dinghy-champs,...,s10/icsa-gill-coed-dinghy-champs/5A,2010-06-01,5,Boston College,boston-college,420,Eagles,1.770488e+09,Unknown,Lucy Wallace-Boston College
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459889,17.0,B,Julia Rosen,julia-rosen,julia-rosen,26,Crew,Nate Powers,Hawaii,s26/peter-wenner-rainbow-invite,...,s26/peter-wenner-rainbow-invite/7B,2026-01-17,7,UC San Diego,uc-san-diego,FJ,Tritons,1.771031e+09,nate-powers,nate-powers
1459890,18.0,B,Julia Rosen,julia-rosen,julia-rosen,26,Crew,Nate Powers,Hawaii,s26/peter-wenner-rainbow-invite,...,s26/peter-wenner-rainbow-invite/8B,2026-01-17,8,UC San Diego,uc-san-diego,FJ,Tritons,1.771031e+09,nate-powers,nate-powers
1459891,16.0,B,Thomas Murphy,thomas-murphy,thomas-murphy,26,Crew,Marina Robalino,Hawaii,s26/peter-wenner-rainbow-invite,...,s26/peter-wenner-rainbow-invite/9B,2026-01-17,9,UC San Diego,uc-san-diego,FJ,Tritons,1.771031e+09,marina-robalino-2027,marina-robalino-2027
1459892,17.0,B,Thomas Murphy,thomas-murphy,thomas-murphy,26,Crew,Marina Robalino,Hawaii,s26/peter-wenner-rainbow-invite,...,s26/peter-wenner-rainbow-invite/10B,2026-01-17,10,UC San Diego,uc-san-diego,FJ,Tritons,1.771031e+09,marina-robalino-2027,marina-robalino-2027
1459893,19.0,B,Thomas Murphy,thomas-murphy,thomas-murphy,26,Crew,Marina Robalino,Hawaii,s26/peter-wenner-rainbow-invite,...,s26/peter-wenner-rainbow-invite/11B,2026-01-17,11,UC San Diego,uc-san-diego,FJ,Tritons,1.771031e+09,marina-robalino-2027,marina-robalino-2027

In [11]:
for i, row in df_sailor_ratings.iterrows():
    print(row['key'])
    break

gabriel-gabe-morreale-2028

In [15]:
cDict = df_sailor_ratings.loc[df_sailor_ratings['key'] == 'carter-anderson'].iloc[0].to_dict()

In [ ]:
def makeSailorFromDict(inDict):
    model = config.model
    mu = model.mu

    return Sailor(inDict['Sailor'], inDict['key'], inDict['gender'], inDict['GradYear'], inDict['Links'], inDict['Teams'], inDict['Seasons'], inDict['Races'], inDict['Rivals'],     
                PlackettLuceRating(inDict['srMU'], inDict['srSigma']),
                PlackettLuceRating(inDict['crMU'], inDict['crSigma']),
                PlackettLuceRating(inDict['wsrMU'], inDict['wsrSigma']),
                PlackettLuceRating(inDict['wcrMU'], inDict['wcrSigma']),
                PlackettLuceRating(inDict['tsrMU'], inDict['tsrSigma']),
                PlackettLuceRating(inDict['tcrMU'], inDict['tcrSigma']),
                PlackettLuceRating(inDict['wtsrMU'], inDict['wtsrSigma']),
                PlackettLuceRating(inDict['wtcrMU'], inDict['wtcrSigma']), inDict['Cross'], inDict['outLinks'], inDict['SkipperRank'], inDict['CrewRank'], inDict['WomenSkipperRank'], inDict['WomenCrewRank'], inDict['TRSkipperRank'], inDict['TRCrewRank'],inDict['TRWomenSkipperRank'], inDict['TRWomenCrewRank'], inDict['skipperAvgRatio'], inDict['crewAvgRatio'])

In [37]:
import Sailors
importlib.reload(Sailors)
from Sailors import Sailor

cObj = makeSailorFromDict(cDict)

cObj.calculateAllRivals(df_racesfr)

{'Skipper': {'eric-anderson-2026': {'name': 'Erik Anderson',
   'races': {'f23': 6},
   'team': 'Hawaii',
   'wins': {'f23': 1}},
  'henry-boeger': {'name': 'Henry Boeger',
   'races': {'f23': 6, 's24': 8},
   'team': 'UC Santa Barbara',
   'wins': {'f23': 2, 's24': 1}},
  'nicholas-mueller': {'name': 'Nicholas Mueller',
   'races': {'f23': 6, 's24': 17},
   'team': 'Cal Maritime',
   'wins': {'f23': 3, 's24': 0}},
  'hudson-mayfield': {'name': 'Hudson Mayfield',
   'races': {'f23': 6, 's24': 12},
   'team': 'Southern Cal',
   'wins': {'f23': 4, 's24': 2}},
  'braedon-hansen': {'name': 'Braedon Hansen',
   'races': {'f23': 6, 's24': 8},
   'team': 'UC Davis',
   'wins': {'f23': 5, 's24': 6}},
  'max-case': {'name': 'Max Case',
   'races': {'f23': 6, 's24': 9},
   'team': 'Cal Poly',
   'wins': {'f23': 4, 's24': 4}},
  'maxwell-miller-2025': {'name': 'Maxwell Miller',
   'races': {'f23': 6, 's24': 10},
   'team': 'Washington',
   'wins': {'f23': 3, 's24': 1}},
  'nicholas-chesemore': {'name': 'Nicholas Chesemore',
   'races': {'f23': 6, 'f25': 5},
   'team': 'Northwestern',
   'wins': {'f23': 4, 'f25': 3}},
  'will-cornell': {'name': 'Will Cornell',
   'races': {'f23': 4},
   'team': 'Berkeley',
   'wins': {'f23': 4}},
  'Arin Bekem-UC Irvine': {'name': 'Arin Bekem',
   'races': {'f23': 6, 's24': 4},
   'team': 'UC Irvine',
   'wins': {'f23': 3, 's24': 4}},
  'linnea-jackson': {'name': 'Linnea Jackson',
   'races': {'f23': 6},
   'team': 'UC Los Angeles',
   'wins': {'f23': 3}},
  'sterling-maggard': {'name': 'Sterling Maggard',
   'races': {'f23': 16, 's24': 1},
   'team': 'Channel Islands',
   'wins': {'f23': 6, 's24': 0}},
  'mitchell-powers': {'name': 'Mitchell Powers',
   'races': {'f23': 6},
   'team': 'Arizona State',
   'wins': {'f23': 5}},
  'oliver-fenner': {'name': 'Oliver Fenner',
   'races': {'f23': 4},
   'team': 'Texas',
   'wins': {'f23': 4}},
  'audra-spokas-jaros': {'name': 'Audra Spokas-jaros',
   'races': {'f23': 4, 's24': 4},
   'team': 'UC San Diego',
   'wins': {'f23': 4, 's24': 4}},
  'enzo-cremers': {'name': 'Enzo Cremers',
   'races': {'f23': 2, 's24': 13},
   'team': 'Berkeley',
   'wins': {'f23': 2, 's24': 9}},
  'caroline-dubois-weber': {'name': 'Caroline DuBois-Weber',
   'races': {'f23': 2},
   'team': 'Texas',
   'wins': {'f23': 2}},
  'ian-johnston': {'name': 'Ian Johnston',
   'races': {'f23': 2},
   'team': 'UC San Diego',
   'wins': {'f23': 2}},
  'jack-phibbs': {'name': 'Jack Phibbs',
   'races': {'f23': 10},
   'team': 'Cal Poly',
   'wins': {'f23': 2}},
  'sam-jennings': {'name': 'Sam Jennings',
   'races': {'f23': 10},
   'team': 'Cal Maritime',
   'wins': {'f23': 2}},
  'summer-drake': {'name': 'Summer Drake',
   'races': {'f23': 10},
   'team': 'UC Santa Cruz',
   'wins': {'f23': 1}},
  'alyssa-cunningham-barkus': {'name': 'Alyssa Cunningham Barkus',
   'races': {'f23': 10},
   'team': 'Berkeley',
   'wins': {'f23': 3}},
  'manuel-mackenna': {'name': 'Manuel Mackenna',
   'races': {'f23': 10},
   'team': 'UC Davis',
   'wins': {'f23': 8}},
  'garrett-henderson': {'name': 'Garrett Henderson',
   'races': {'f23': 10},
   'team': 'Cal Poly',
   'wins': {'f23': 1}},
  'lucas-kasper': {'name': 'Lucas Kasper',
   'races': {'f23': 10},
   'team': 'Cal Poly',
   'wins': {'f23': 3}},
  'paige-odell': {'name': 'Paige O’Dell',
   'races': {'f23': 10},
   'team': 'Cal Poly',
   'wins': {'f23': 7}},
  'andrew-down': {'name': 'Andrew Down',
   'races': {'f23': 10},
   'team': 'Arizona State',
   'wins': {'f23': 4}},
  'zoe-flemate': {'name': 'Zoe Flemate',
   'races': {'f23': 10},
   'team': 'Berkeley',
   'wins': {'f23': 7}},
  'andrew-bistras': {'name': 'Andrew Bistras',
   'races': {'f23': 10},
   'team': 'UC Los Angeles',
   'wins': {'f23': 7}},
  'william-bailly': {'name': 'William Bailly',
   'races': {'f23': 10},
   'team': 'Arizona State',
   'wins': {'f23': 6}},
  'gavin-hirz': {'name': 'Gavin Hirz',
   'races': {'f23': 10, 's24': 4},
   'team': 'Arizona State',
   'wins': {'f23': 7, 's24': 4}},
  'brayden-money': {'name': 'Brayden Money',
   'races': {'f23': 10},
   'team': 'UC Irvine',
   'wins': {'f23': 8}},
  'alexandra-toaxen': {'name': 'Alexandra Toaxen',
   'races': {'f23': 10, 's24': 12},
   'team': 'UC Los Angeles',
   'wins': {'f23': 8, 's24': 12}},
  'adem-evecek': {'name': 'Adem Evecek',
   'races': {'f23': 10},
   'team': 'UC San Diego',
   'wins': {'f23': 8}},
  'Claire Desbaillets-UC Davis': {'name': 'Claire Desbaillets',
   'races': {'f23': 10},
   'team': 'UC Davis',
   'wins': {'f23': 8}},
  'gillian-cate': {'name': 'Gillian Cate',
   'races': {'f23': 10},
   'team': 'Arizona State',
   'wins': {'f23': 8}},
  'mason-read': {'name': 'Mason Read',
   'races': {'f23': 2},
   'team': 'UC Irvine',
   'wins': {'f23': 0}},
  'michael-jacobson': {'name': 'Michael Jacobson',
   'races': {'f23': 8},
   'team': 'UC Irvine',
   'wins': {'f23': 8}},
  'luke-harris': {'name': 'Luke Harris',
   'races': {'s24': 9},
   'team': 'Southern Cal',
   'wins': {'s24': 2}},
  'blake-roberts': {'name': 'Blake Roberts',
   'races': {'s24': 9},
   'team': 'UC Santa Cruz',
   'wins': {'s24': 4}},
  'marianna-shand': {'name': 'Marianna Shand',
   'races': {'s24': 9},
   'team': 'UC Los Angeles',
   'wins': {'s24': 2}},
  'matt-grimsley': {'name': 'Matt Grimsley',
   'races': {'s24': 9},
   'team': 'Arizona State',
   'wins': {'s24': 2}},
  'ximena-greatorex': {'name': 'Ximena Greatorex',
   'races': {'s24': 4},
   'team': 'Cal Poly',
   'wins': {'s24': 4}},
  'katherine-olsen': {'name': 'Katherine Olsen',
   'races': {'s24': 9},
   'team': 'Berkeley',
   'wins': {'s24': 5}},
  'nikita-swatek': {'name': 'Nikita Swatek',
   'races': {'s24': 18},
   'team': 'UC Irvine',
   'wins': {'s24': 18}},
  'rory-collins': {'name': 'Rory Collins',
   'races': {'s24': 9},
   'team': 'UC Santa Barbara',
   'wins': {'s24': 7}},
  'brendan-oconnor-2027': {'name': "Brendan O'Connor",
   'races': {'s24': 9},
   'team': 'UC San Diego',
   'wins': {'s24': 6}},
  'katherine-smith': {'name': 'Katherine Smith',
   'races': {'s24': 17},
   'team': 'UC Los Angeles',
   'wins': {'s24': 17}},
  'gennis-marie-pilapil': {'name': 'Gennis Marie Pilapil',
   'races': {'s24': 17},
   'team': 'UC Irvine',
   'wins': {'s24': 17}},
  'nejan-gunawardena': {'name': 'Nejan Gunawardena',
   'races': {'s24': 17},
   'team': 'UC Irvine',
   'wins': {'s24': 17}},
  'florence-duff': {'name': 'Florence Duff',
   'races': {'s24': 17},
   'team': 'Cal Poly',
   'wins': {'s24': 8}},
  'chase-vanderveer': {'name': 'Chase VanDerveer',
   'races': {'s24': 1},
   'team': 'Santa Clara',
   'wins': {'s24': 1}},
  'ricky-miller': {'name': 'Ricky Miller',
   'races': {'s24': 8},
   'team': 'Rice',
   'wins': {'s24': 3}},
  'grace-richie': {'name': 'Grace Richie',
   'races': {'s24': 8},
   'team': 'UC San Diego',
   'wins': {'s24': 8}},
  'morgana-manti': {'name': 'Morgana Manti',
   'races': {'s24': 4},
   'team': 'Southern Cal',
   'wins': {'s24': 2}},
  'colin-olson-2026': {'name': 'Colin Olson',
   'races': {'s24': 4},
   'team': 'UC Santa Cruz',
   'wins': {'s24': 2}},
  'jack-kisling': {'name': 'Jack Kisling',
   'races': {'s24': 4},
   'team': 'Cal Poly',
   'wins': {'s24': 2}},
  'brandon-stadtherr': {'name': 'Brandon Stadtherr',
   'races': {'s24': 12},
   'team': 'Channel Islands',
   'wins': {'s24': 10}},
  'christopher-shintani-2020': {'name': 'Christopher Shintani',
   'races': {'s24': 4},
   'team': 'Cal Maritime',
   'wins': {'s24': 4}},
  'edward-ansart': {'name': 'Edward Ansart',
   'races': {'s24': 4},
   'team': 'Southern Cal',
   'wins': {'s24': 4}},
  'sean-lipps': {'name': 'Sean Lipps',
   'races': {'s24': 4},
   'team': 'UC San Diego',
   'wins': {'s24': 4}},
  'alexander-lohan': {'name': 'Alexander Lohan',
   'races': {'s24': 4},
   'team': 'UC Davis',
   'wins': {'s24': 4}},
  'lucas-woodworth': {'name': 'Lucas Woodworth',
   'races': {'s24': 7},
   'team': 'Stanford',
   'wins': {'s24': 0}},
  'trey-summers': {'name': 'Trey Summers',
   'races': {'s24': 8},
   'team': 'Hawaii',
   'wins': {'s24': 0}},
  'clay-myers': {'name': 'Clay Myers',
   'races': {'s24': 8},
   'team': 'Cal Maritime',
   'wins': {'s24': 0}},
  'wilton-lawton': {'name': 'Wilton Lawton',
   'races': {'s24': 8},
   'team': 'Berkeley',
   'wins': {'s24': 1}},
  'juan-casal': {'name': 'Juan Casal',
   'races': {'s24': 8},
   'team': 'Arizona State',
   'wins': {'s24': 3}},
  'robert-bloomfield': {'name': 'Robert Bloomfield',
   'races': {'s24': 8},
   'team': 'Cal Poly',
   'wins': {'s24': 2}},
  'mary-darcy': {'name': 'Mary d’Arcy',
   'races': {'s24': 8},
   'team': 'Western Washington',
   'wins': {'s24': 2}},
  'adam-leddy': {'name': 'Adam Leddy',
   'races': {'s24': 8},
   'team': 'UC Irvine',
   'wins': {'s24': 5}},
  'tegan-smith': {'name': 'Tegan Smith',
   'races': {'s24': 2},
   'team': 'San Diego State',
   'wins': {'s24': 1}},
  'alex-bussey': {'name': 'Alex Bussey',
   'races': {'s24': 8},
   'team': 'UC San Diego',
   'wins': {'s24': 8}},
  'owen-gormely': {'name': 'Owen Gormely',
   'races': {'s24': 6},
   'team': 'San Diego State',
   'wins': {'s24': 6}},
  'oliver-nairn': {'name': 'Oliver Nairn',
   'races': {'s24': 16},
   'team': 'Washington',
   'wins': {'s24': 4}},
  'sanchita-pant': {'name': 'Sanchita Pant',
   'races': {'s24': 4},
   'team': 'UC Los Angeles',
   'wins': {'s24': 2}},
  'shay-wood-2027': {'name': 'Shay Wood',
   'races': {'s24': 1},
   'team': 'Stanford',
   'wins': {'s24': 1}},
  'benjamin-stone': {'name': 'Benjamin Stone',
   'races': {'s24': 12},
   'team': 'Washington',
   'wins': {'s24': 2}},
  'nathan-gerber': {'name': 'Nathan Gerber',
   'races': {'s24': 12},
   'team': 'Western Washington',
   'wins': {'s24': 6}},
  'emily-smith-washington': {'name': 'Emily Smith',
   'races': {'s24': 12},
   'team': 'Washington',
   'wins': {'s24': 9}},
  'ellie-blakemore': {'name': 'Ellie Blakemore',
   'races': {'s24': 12},
   'team': 'Western Washington',
   'wins': {'s24': 4}},
  'george-warfel': {'name': 'George Warfel',
   'races': {'s24': 12},
   'team': 'Northwestern',
   'wins': {'s24': 10}},
  'jaden-unruh': {'name': 'Jaden Unruh',
   'races': {'s24': 12},
   'team': 'Washington',
   'wins': {'s24': 10}},
  'emily-avey': {'name': 'Emily Avey',
   'races': {'s24': 12},
   'team': 'Oregon',
   'wins': {'s24': 6}},
  'rachel-bartel': {'name': 'Rachel Bartel',
   'races': {'s24': 12},
   'team': 'Saint Thomas',
   'wins': {'s24': 6}},
  'molly-mcleod': {'name': 'Molly McLeod',
   'races': {'s24': 10},
   'team': 'Oregon',
   'wins': {'s24': 9}},
  'Peter Hall-Western Washington': {'name': 'Peter Hall',
   'races': {'s24': 12},
   'team': 'Western Washington',
   'wins': {'s24': 11}},
  'conrad-kistler': {'name': 'Conrad Kistler',
   'races': {'s24': 12},
   'team': 'UC Los Angeles',
   'wins': {'s24': 12}},
  'enzo-dougherty': {'name': 'Enzo Dougherty',
   'races': {'s24': 6},
   'team': 'Washington',
   'wins': {'s24': 6}},
  'ella-notdurft': {'name': 'ella notdurft',
   'races': {'s24': 2},
   'team': 'Oregon',
   'wins': {'s24': 2}},
  'ethan-lisle': {'name': 'Ethan Lisle',
   'races': {'s24': 9},
   'team': 'Berkeley',
   'wins': {'s24': 8}},
  'samuel-groom': {'name': 'Samuel Groom',
   'races': {'s24': 9},
   'team': 'Cal Poly',
   'wins': {'s24': 8}},
  'caden-domingo': {'name': 'Caden Domingo',
   'races': {'s24': 9},
   'team': 'UC Santa Cruz',
   'wins': {'s24': 9}},
  'liam-williams': {'name': 'Liam Williams',
   'races': {'s24': 9},
   'team': 'UC Los Angeles',
   'wins': {'s24': 8}},
  'mira-shupe': {'name': 'Mira Shupe',
   'races': {'s24': 9},
   'team': 'Cal Poly',
   'wins': {'s24': 9}},
  'matthew-stank': {'name': 'Matthew Stank',
   'races': {'s24': 8},
   'team': 'UC Irvine',
   'wins': {'s24': 8}},
  'paul-munsell': {'name': 'Paul Munsell',
   'races': {'s24': 9},
   'team': 'Cal Poly',
   'wins': {'s24': 9}},
  'chloe-lighterink': {'name': 'Chloe Lighterink',
   'races': {'s24': 9},
   'team': 'UC Davis',
   'wins': {'s24': 9}},
  'nathan-baer': {'name': 'Nathan Baer',
   'races': {'s24': 9},
   'team': 'UC Davis',
   'wins': {'s24': 9}},
  'nathan-selian': {'name': 'Nathan Selian',
   'races': {'f24': 18},
   'team': 'Boston University',
   'wins': {'f24': 6}},
  'shea-mcgrath': {'name': 'Shea McGrath',
   'races': {'f24': 23},
   'team': 'Bowdoin',
   'wins': {'f24': 9}},
  'gavin-sanborn': {'name': 'Gavin Sanborn',
   'races': {'f24': 4},
   'team': 'Vermont',
   'wins': {'f24': 0}},
  'carter-anderson-2027': {'name': 'Carter Anderson',
   'races': {'f24': 42, 's25': 6, 'f25': 33},
   'team': 'Northeastern',
   'wins': {'f24': 0, 's25': 0, 'f25': 0}},
  'will-eggena': {'name': 'Will Eggena',
   'races': {'f24': 13},
   'team': 'Dartmouth',
   'wins': {'f24': 10}},
  'riley-donahue': {'name': 'Riley Donahue',
   'races': {'f24': 4},
   'team': 'Bowdoin',
   'wins': {'f24': 1}},
  'ted-richardsson': {'name': 'Ted Richardsson',
   'races': {'f24': 4, 'f25': 5},
   'team': 'New Hampshire',
   'wins': {'f24': 4, 'f25': 5}},
  'marykate-hanus': {'name': 'Marykate Hanus',
   'races': {'f24': 13},
   'team': 'New Hampshire',
   'wins': {'f24': 6}},
  'griffin-stolp': {'name': 'Griffin Stolp',
   'races': {'f24': 14},
   'team': 'Maine Maritime',
   'wins': {'f24': 11}},
  'andrew-blagden': {'name': 'Andrew Blagden',
   'races': {'f24': 4},
   'team': 'Bentley',
   'wins': {'f24': 4}},
  'georgia-green': {'name': 'Georgia Green',
   'races': {'f24': 4},
   'team': 'Bates',
   'wins': {'f24': 4}},
  'kevin-mcneill': {'name': 'Kevin McNeill',
   'races': {'f24': 4, 'f25': 12},
   'team': 'Mass Maritime',
   'wins': {'f24': 4, 'f25': 11}},
  'felix-nusbaum-2025': {'name': 'Felix Nusbaum',
   'races': {'f24': 4},
   'team': 'Williams',
   'wins': {'f24': 4}},
  'aengus-onken': {'name': 'Aengus Onken',
   'races': {'f24': 4},
   'team': 'Middlebury',
   'wins': {'f24': 4}},
  'courtland-doyle': {'name': 'Courtland Doyle',
   'races': {'f24': 10, 'f25': 8},
   'team': 'Tufts',
   'wins': {'f24': 2, 'f25': 1}},
  'andy-yu': {'name': 'Andy Yu',
   'races': {'f24': 16, 'f25': 5},
   'team': 'MIT',
   'wins': {'f24': 1, 'f25': 2}},
  'rogelio-casellas': {'name': 'Rogelio Casellas',
   'races': {'f24': 10, 's25': 6, 'f25': 12},
   'team': 'Boston College',
   'wins': {'f24': 1, 's25': 1, 'f25': 6}},
  'alex-lech': {'name': 'Alex Lech',
   'races': {'f24': 23},
   'team': 'Boston College',
   'wins': {'f24': 3}},
  'edward-herman': {'name': 'Edward Herman',
   'races': {'f24': 10},
   'team': 'Roger Williams',
   'wins': {'f24': 1}},
  'tristan-mcdonald': {'name': 'Tristan McDonald',
   'races': {'f24': 10},
   'team': 'Roger Williams',
   'wins': {'f24': 2}},
  'jean-luc-depardieu': {'name': 'Jean-Luc Depardieu',
   'races': {'f24': 10},
   'team': 'Brown',
   'wins': {'f24': 5}},
  'charlotte-west': {'name': 'Charlotte West',
   'races': {'f24': 10},
   'team': 'Dartmouth',
   'wins': {'f24': 3}},
  'buck-rathbun': {'name': 'Buck Rathbun',
   'races': {'f24': 10, 'f25': 7},
   'team': 'Boston University',
   'wins': {'f24': 3, 'f25': 6}},
  'sophia-woodbury': {'name': 'Sophia Woodbury',
   'races': {'f24': 10},
   'team': 'MIT',
   'wins': {'f24': 4}},
  'conrad-straden': {'name': 'Conrad Straden',
   'races': {'f24': 6},
   'team': 'MIT',
   'wins': {'f24': 1}},
  'zach-earnshaw': {'name': 'Zach Earnshaw',
   'races': {'f24': 19},
   'team': 'Mass Maritime',
   'wins': {'f24': 16}},
  'jordynn-johnson': {'name': 'Jordynn Johnson',
   'races': {'f24': 10},
   'team': 'Vermont',
   'wins': {'f24': 7}},
  'benjamin-ely': {'name': 'Benjamin Ely',
   'races': {'f24': 10},
   'team': 'Olin',
   'wins': {'f24': 7}},
  'brett-tardie': {'name': 'Brett Tardie',
   'races': {'f24': 10},
   'team': 'Bentley',
   'wins': {'f24': 6}},
  'james-frady': {'name': 'James Frady',
   'races': {'f24': 10, 'f25': 12},
   'team': 'New Hampshire',
   'wins': {'f24': 9, 'f25': 10}},
  'tyler-winowiecki': {'name': 'Tyler Winowiecki',
   'races': {'f24': 8},
   'team': 'Salve Regina',
   'wins': {'f24': 6}},
  'alyson-liu': {'name': 'Alyson Liu',
   'races': {'f24': 10},
   'team': 'U. Connecticut',
   'wins': {'f24': 9}},
  'karya-basaraner': {'name': 'Karya Basaraner',
   'races': {'f24': 4, 's25': 6},
   'team': 'MIT',
   'wins': {'f24': 1, 's25': 3}},
  'olivia-blackmer': {'name': 'Olivia Blackmer',
   'races': {'f24': 2},
   'team': 'Salve Regina',
   'wins': {'f24': 1}},
  'peter-joslin': {'name': 'Peter Joslin',
   'races': {'f24': 9, 'f25': 5},
   'team': 'Boston College',
   'wins': {'f24': 0, 'f25': 0}},
  'kate-danielson': {'name': 'Kate Danielson',
   'races': {'f24': 9},
   'team': 'Harvard',
   'wins': {'f24': 1}},
  'grant-schmidt': {'name': 'Grant Schmidt',
   'races': {'f24': 9},
   'team': 'Tufts',
   'wins': {'f24': 3}},
  'david-vinogradov': {'name': 'David Vinogradov',
   'races': {'f24': 5},
   'team': 'Coast Guard',
   'wins': {'f24': 1}},
  'william-gear': {'name': 'William Gear',
   'races': {'f24': 5, 'f25': 2},
   'team': 'Vermont',
   'wins': {'f24': 3, 'f25': 2}},
  'patricia-winssinger': {'name': 'Patricia Winssinger',
   'races': {'f24': 9},
   'team': 'Tufts',
   'wins': {'f24': 4}},
  'henry-parker': {'name': 'Henry Parker',
   'races': {'f24': 9, 'f25': 5},
   'team': 'Citadel',
   'wins': {'f24': 6, 'f25': 5}},
  'nate-ingebritson': {'name': 'Nate Ingebritson',
   'races': {'f24': 9},
   'team': 'Berkeley',
   'wins': {'f24': 5}},
  'sean-bascoe': {'name': 'Sean Bascoe',
   'races': {'f24': 9},
   'team': 'Northwestern',
   'wins': {'f24': 9}},
  'joey-richardson': {'name': 'Joey Richardson',
   'races': {'f24': 4},
   'team': 'Coast Guard',
   'wins': {'f24': 1}},
  'marco-welch': {'name': 'Marco Welch',
   'races': {'f24': 4},
   'team': 'Vermont',
   'wins': {'f24': 2}},
  'Isaac Thompson-Maine Maritime': {'name': 'Isaac Thompson',
   'races': {'f24': 5},
   'team': 'Maine Maritime',
   'wins': {'f24': 5}},
  'enzo-menditto': {'name': 'Enzo Menditto',
   'races': {'f24': 5},
   'team': 'Georgetown',
   'wins': {'f24': 1}},
  'sidney-moyer': {'name': 'Sidney Moyer',
   'races': {'f24': 11},
   'team': 'Brown',
   'wins': {'f24': 2}},
  'connor-mchugh': {'name': 'Connor McHugh',
   'races': {'f24': 5, 'f25': 10},
   'team': 'Roger Williams',
   'wins': {'f24': 3, 'f25': 1}},
  'calvin-schmid': {'name': 'Calvin Schmid',
   'races': {'f24': 5},
   'team': 'Webb Institute',
   'wins': {'f24': 1}},
  'tyler-lamm': {'name': 'Tyler Lamm',
   'races': {'f24': 5, 'f25': 2},
   'team': 'Brown',
   'wins': {'f24': 3, 'f25': 2}},
  'elliott-mendenhall': {'name': 'Elliott Mendenhall',
   'races': {'f24': 5},
   'team': 'Boston University',
   'wins': {'f24': 1}},
  'gus-macaulay': {'name': 'Gus Macaulay',
   'races': {'f24': 5},
   'team': 'Tufts',
   'wins': {'f24': 1}},
  'william-kulas': {'name': 'William Kulas',
   'races': {'f24': 13, 'f25': 2},
   'team': 'MIT',
   'wins': {'f24': 2, 'f25': 0}},
  'olivia-lowthian': {'name': 'Olivia Lowthian',
   'races': {'f24': 5},
   'team': 'Salve Regina',
   'wins': {'f24': 3}},
  'caylin-schnoor': {'name': 'Caylin Schnoor',
   'races': {'f24': 5},
   'team': 'Roger Williams',
   'wins': {'f24': 3}},
  'kiana-beachy': {'name': 'Kiana Beachy',
   'races': {'f24': 11, 'f25': 12},
   'team': 'Tufts',
   'wins': {'f24': 5, 'f25': 7}},
  'greta-shuster': {'name': 'Greta Shuster',
   'races': {'f24': 5},
   'team': 'Bates',
   'wins': {'f24': 5}},
  'ben-sheppard': {'name': 'Ben Sheppard',
   'races': {'f24': 8, 'f25': 6},
   'team': 'Dartmouth',
   'wins': {'f24': 2, 'f25': 0}},
  'mathias-reimer': {'name': 'Mathias Reimer',
   'races': {'f24': 8},
   'team': 'Yale',
   'wins': {'f24': 2}},
  'jack-flores': {'name': 'Jack Flores',
   'races': {'f24': 8},
   'team': 'Tufts',
   'wins': {'f24': 3}},
  'cam-spriggs': {'name': 'Cam Spriggs',
   'races': {'f24': 2},
   'team': 'Brown',
   'wins': {'f24': 0}},
  'luke-zylinski': {'name': 'Luke Zylinski',
   'races': {'f24': 8, 'f25': 2},
   'team': 'Coast Guard',
   'wins': {'f24': 1, 'f25': 0}},

In [15]:
# [r for r in cObj.races if r['type'] == 'fleet'][-1]
cObj.getRating('skipper', 'fleet', False, True, config)

1611.2889458679997

In [8]:
df_races = pd.read_parquet('./../postcalcfrraces.parquet')
df_races

,raceID,season,regatta,raceNumber,div,sailorID,partnerID,partnerName,score,predicted,...,date,scoring,venue,boat,boatName,ratingType,oldRating,newRating,regAvg:,calculatedAt
0,s10/harris-l-kempner/5B,s10,harris-l-kempner,5,B,Justin Ogden-Texas,Unknown,Brandon Fiew,5,1,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 1,sr,1000.000000,1097.767333,1000.0,1.771281e+09
1,s10/harris-l-kempner/5B,s10,harris-l-kempner,5,B,Pierre Rochard-Texas,Unknown,Unknown,11,2,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 2,sr,1000.000000,956.383077,1000.0,1.771281e+09
2,s10/harris-l-kempner/6B,s10,harris-l-kempner,6,B,Justin Ogden-Texas,Unknown,Unknown,5,1,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 1,sr,1097.767333,1172.116321,1000.0,1.771281e+09
3,s10/harris-l-kempner/6B,s10,harris-l-kempner,6,B,Pierre Rochard-Texas,Unknown,Unknown,11,2,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 2,sr,956.383077,930.268574,1000.0,1.771281e+09
4,s10/harris-l-kempner/7B,s10,harris-l-kempner,7,B,Justin Ogden-Texas,Unknown,Unknown,6,1,...,2010-02-06,2 Divisions,Texas A&M Galveston,,Longhorns 1,sr,1172.116321,1228.541984,1000.0,1.771281e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194610,s26/mustang-open-varsity/8B,s26,mustang-open-varsity,8,B,catherine-arcaris,amelia-gassner,Amelia Gassner,7,6,...,2026-02-07,2 Divisions,Cal Poly,,Bears 2,cr,1298.909498,1306.377154,1000.0,1.771281e+09
1194611,s26/mustang-open-varsity/8B,s26,mustang-open-varsity,8,B,thomas-murphy,jp-finnegan,JP Finnegan,11,8,...,2026-02-07,2 Divisions,Cal Poly,,Tritons 1,cr,1015.130173,1002.609200,1000.0,1.771281e+09
1194612,s26/mustang-open-varsity/8B,s26,mustang-open-varsity,8,B,caroline-crowe,gwen-hildebrand,Gwen Hildebrand,12,14,...,2026-02-07,2 Divisions,Cal Poly,,Aggies,cr,690.655446,690.742353,1000.0,1.771281e+09
1194613,s26/mustang-open-varsity/8B,s26,mustang-open-varsity,8,B,kieran-mcewen,claire-wiley-2027,Claire Wiley,16,12,...,2026-02-07,2 Divisions,Cal Poly,,Colts,cr,874.791066,799.894934,1000.0,1.771281e+09
1194614,s26/mustang-open-varsity/8B,s26,mustang-open-varsity,8,B,lance-lin,cole-mitchell,Cole Mitchell,14,11,...,2026-02-07,2 Divisions,Cal Poly,,Broncos,cr,771.591728,735.296442,1000.0,1.771281e+09

In [47]:
df_racesfr['Date'].iloc[0].value

1275350400000000000

# Rivals testing

In [12]:
df_rivals = pd.read_parquet('./../rivalstesting.parquet')
df_rivals

,sailor_key,opponent_key,opponent_fullname,opponent_team,position,season,total,wins
0,Eliza Richartz-Stanford,Kelsey Rupp-Southern Cal,Kelsey Rupp,Southern Cal,Skipper,f10,12,6
1,Kelsey Rupp-Southern Cal,Eliza Richartz-Stanford,Eliza Richartz,Stanford,Skipper,f10,12,6
2,Eliza Richartz-Stanford,Hannah Tuson-Turner-Hawaii,Hannah Tuson-Turner,Hawaii,Skipper,f10,12,5
3,Hannah Tuson-Turner-Hawaii,Eliza Richartz-Stanford,Eliza Richartz,Stanford,Skipper,f10,12,7
4,Eliza Richartz-Stanford,Ashley Eberhard-Monterey Bay,Ashley Eberhard,Monterey Bay,Skipper,f10,12,11
...,...,...,...,...,...,...,...,...
2983427,essie-clifton,sophia-pearce,Sophia Pearce,Cornell,Crew,s25,1,0
2983428,sophia-pearce,hope-breslin,Hope Breslin,Tulane,Crew,s25,1,1
2983429,hope-breslin,sophia-pearce,Sophia Pearce,Cornell,Crew,s25,1,0
2983430,amelia-neumann,essie-clifton,Essie Clifton,Tulane,Crew,s25,1,1
2983431,essie-clifton,amelia-neumann,Amelia Neumann,Cornell,Crew,s25,1,0